questions = {
    "Culture": [
        "How does cultural heritage influence modern societal values?",
        "In what ways does art preserve traditional customs?",
        "How do cultural festivals contribute to community identity?",
        "What role does language play in shaping cultural identity?",
        "How is globalization affecting local cultural practices?",
        "How does cultural appropriation impact society?",
        "What is the influence of cultural icons on youth?",
        "How do multicultural societies navigate cultural differences?",
        "What is the role of museums in preserving cultural history?",
        "How do cultural narratives shape national identity?"
    ],
    "Sports": [
        "How do sports foster national pride and unity?",
        "What is the impact of commercialization on athletic performance?",
        "How does doping controversy affect public trust in sports?",
        "In what ways do major sporting events influence local economies?",
        "How do different cultures perceive competitive sports?",
        "What role do sports scandals play in shaping fan behavior?",
        "How is technology revolutionizing sports training and performance?",
        "What is the future of esports in traditional sports culture?",
        "How do athlete endorsements affect consumer behavior?",
        "What challenges face sports governance in the modern era?"
    ],
    "Future of Humanity": [
        "What are the greatest challenges facing humanity in the next century?",
        "How might artificial intelligence transform human society?",
        "What role will space colonization play in our future?",
        "How can humanity prepare for potential global crises?",
        "What are the ethical implications of human genetic modification?",
        "How will climate change reshape geopolitical landscapes?",
        "What future technologies could revolutionize daily life?",
        "How might resource scarcity drive international conflict?",
        "What is the impact of demographic shifts on society's future?",
        "How does the future of work evolve with technological advances?"
    ],
    "Politics": [
        "How do political ideologies shape public policy in the modern era?",
        "What factors contribute to increasing political polarization?",
        "How does social media influence political discourse?",
        "What is the impact of populist movements on democratic institutions?",
        "How do political scandals affect public trust?",
        "What are the implications of election interference?",
        "How does political satire reflect and influence societal change?",
        "What is the role of international organizations in global governance?",
        "How do media biases influence political polarization?",
        "What are the prospects for bipartisan cooperation in current politics?"
    ],
    "Economics": [
        "How do economic policies influence income inequality?",
        "What is the impact of globalization on local and global economies?",
        "How do technological advancements drive economic growth?",
        "What role do financial regulations play in ensuring economic stability?",
        "How do trade wars affect international markets?",
        "What are the effects of taxation on consumer behavior?",
        "How does automation reshape job markets and income distribution?",
        "What is the impact of digital currencies on traditional banking systems?",
        "How do economic sanctions influence international relations?",
        "What challenges do emerging markets face in the global economy?"
    ],
    "Technology": [
        "How is emerging technology transforming everyday life?",
        "What are the societal implications of widespread AI adoption?",
        "How do cybersecurity threats affect technological progress?",
        "What is the role of big data in shaping technology trends?",
        "How does the Internet of Things (IoT) revolutionize consumer behavior?",
        "What are the ethical challenges associated with surveillance technology?",
        "How does blockchain technology disrupt traditional industries?",
        "What is the impact of 5G on global communication networks?",
        "How do advancements in robotics change human labor markets?",
        "What future technologies could redefine human-machine interaction?"
    ],
    "Science": [
        "What recent scientific breakthrough has the potential to reshape our understanding of the universe?",
        "How does interdisciplinary research foster scientific innovation?",
        "What are the challenges in replicating scientific studies?",
        "How does climate research influence public policy?",
        "What ethical dilemmas arise in cutting-edge scientific experiments?",
        "How does scientific funding impact research directions?",
        "What role do private institutions play in advancing science?",
        "How do peer review processes affect the credibility of research?",
        "What are the most promising areas of research in renewable energy?",
        "How do advancements in neuroscience change our understanding of the brain?"
    ],
    "Art": [
        "How do contemporary art movements reflect societal changes?",
        "What role does art play in challenging established cultural norms?",
        "How has digital art transformed traditional artistic expression?",
        "What is the impact of public art on community engagement?",
        "How do art critics influence public perception of creativity?",
        "What controversies exist around art censorship?",
        "How does art serve as a medium for political protest?",
        "What is the significance of art in the age of social media?",
        "How do museums curate exhibitions to educate the public?",
        "What role does performance art play in modern culture?"
    ],
    "History": [
        "What lessons from history are most relevant to solving today's global challenges?",
        "How do historical narratives shape national identity?",
        "What is the role of collective memory in preserving historical events?",
        "How has colonial history influenced modern geopolitical landscapes?",
        "What are the impacts of historical revisionism on contemporary society?",
        "How do historians reconcile objectivity with interpretation?",
        "What can economic crises of the past teach us about future financial stability?",
        "How do major wars shape the trajectory of civilizations?",
        "What is the significance of historical monuments in modern society?",
        "How does the reinterpretation of history affect modern politics?"
    ],
    "Entertainment": [
        "How has the evolution of media influenced modern popular culture?",
        "What role do streaming platforms play in transforming entertainment?",
        "How does celebrity culture affect public perceptions of fame?",
        "In what ways does entertainment shape societal norms?",
        "What controversies surround reality television?",
        "How are video games changing the landscape of storytelling?",
        "What role does social media play in the entertainment industry?",
        "How does digital content challenge traditional media formats?",
        "What trends are emerging in interactive entertainment?",
        "How does entertainment contribute to cultural identity?"
    ],
    "Environment": [
        "What are the most critical environmental challenges of our time?",
        "How does climate change impact global ecosystems?",
        "What policies are most effective in mitigating environmental damage?",
        "How do renewable energy sources compare to fossil fuels?",
        "What is the role of conservation in preserving biodiversity?",
        "How does pollution affect public health and the environment?",
        "What controversies surround environmental regulations?",
        "How can urban planning contribute to a sustainable future?",
        "What impact does deforestation have on global climate patterns?",
        "How do emerging technologies contribute to environmental monitoring?"
    ],
    "Ethics": [
        "What ethical challenges arise from the deployment of AI in society?",
        "How do issues of bias and fairness affect algorithmic decision-making?",
        "What are the implications of surveillance on personal privacy?",
        "How should society balance technological progress with ethical considerations?",
        "What ethical dilemmas are associated with genetic engineering?",
        "How do corporate ethics influence public trust in technology?",
        "What is the role of ethics in data collection and usage?",
        "How do ethical guidelines evolve with technological advancements?",
        "What controversies surround the use of AI in criminal justice?",
        "How can interdisciplinary approaches address ethical challenges in tech?"
    ],
    "Health": [
        "How do emerging medical technologies improve patient outcomes?",
        "What is the impact of digital health tools on healthcare delivery?",
        "How do public health policies affect community well-being?",
        "What challenges exist in the global distribution of vaccines?",
        "How does misinformation affect public health during pandemics?",
        "What role does personalized medicine play in modern healthcare?",
        "How do lifestyle factors influence long-term health outcomes?",
        "What ethical considerations arise in the use of medical data?",
        "How do health disparities manifest across different populations?",
        "What challenges exist in integrating AI into diagnostic processes?"
    ],
    "Education": [
        "How is technology transforming traditional educational models?",
        "What is the role of online learning in increasing accessibility?",
        "How do educational policies affect student performance?",
        "What challenges arise from integrating AI into classrooms?",
        "How does teacher training evolve with technological change?",
        "What impact does educational inequality have on society?",
        "How can curriculum design foster critical thinking?",
        "What role does lifelong learning play in career development?",
        "How do digital tools enhance collaborative learning?",
        "What controversies exist in modern educational practices?"
    ],
    "Social Media": [
        "How does social media shape public discourse?",
        "What are the effects of echo chambers on social media platforms?",
        "How do algorithms influence the diversity of content?",
        "What role does social media play in political polarization?",
        "How does misinformation spread on social media?",
        "What are the privacy concerns associated with social media data?",
        "How do social media trends impact consumer behavior?",
        "What is the effect of influencer culture on society?",
        "How does social media affect mental health?",
        "What are the ethical implications of data mining on social platforms?"
    ]
}